name: Docker Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t unsw-anomaly-detection .

    - name: Run container and test
      run: |
        docker run --rm unsw-anomaly-detection python -c "import pandas; print('✅ Docker image works!')"
